pipeline {
    agent any

    stages {
        stage('Stop nginx process') {
            steps {
                powershell(returnStdout: true, script: 'net stop nginx')
                echo 'The nginx process has been stopped.'
            }
        }

        stage('Checkout Github Project') {
            steps {
                git(url: 'https://github.com/DavidRipFernandez/CleanArchitectureNode', branch: 'main')
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    bat 'npm install'
                }
            }
        }

        stage('Build React App') {
            steps {
                dir('frontend') {
                    bat 'npm run build'
                }
            }
        }

        stage('Clean-Up Old Files') {
            steps {
                powershell(returnStdout: true, script: 'Remove-Item -Path "C:\\nginx\\html\\ca-frontend\\*" -Recurse -Force')
                echo 'Clean-Up done.'
            }
        }

        stage('Copy Build to Nginx') {
            steps {
                script {
                    String command = "Copy-Item -Path \"${WORKSPACE}\\frontend\\build\\*\" -Destination \"C:\\nginx\\html\\ca-frontend\\\" -Recurse -Force"
                    echo command
                    powershell(returnStdout: true, script: command)
                    echo 'Copy files done.'
                }
            }
        }

        stage('Start nginx process') {
            steps {
                powershell(returnStdout: true, script: 'net start nginx')
                echo 'The nginx process has been started.'
            }
        }
    }

    post {
        always {
            echo 'Proceso de despliegue del frontend completado.'
        }
        failure {
            echo 'El despliegue falló, revisa los logs para más detalles.'
        }
    }
}
