pipeline {
    agent any

    environment {
        NODE_HOME = 'C:\\Program Files\\nodejs'
        PATH = "${NODE_HOME};${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/DavidRipFernandez/CleanArchitectureNode.git'
            }
        }

        stage('Instalar dependencias') {
            steps {
                dir('backend') {
                    bat "npm install"
                }
            }
        }

        stage('Levantar backend paralelo') {
            steps {
                parallel(
                    Dev: {
                        dir('backend') {
                            bat "start /B npm run dev"
                        }
                    },
                    Test: {
                        dir('backend') {
                            bat "start /B npm run test"
                        }
                    },
                    Staging: {
                        dir('backend') {
                            bat "start /B npm run staging"
                        }
                    }
                )
            }
        }

        stage('Verificar backend') {
            steps {
                parallel(
                    Dev: {
                        powershell """
                        curl -f http://localhost:3001/swagger
                        """
                    },
                    Test: {
                        powershell """
                        curl -f http://localhost:3002/swagger
                        """
                    },
                    Staging: {
                        powershell """
                        curl -f http://localhost:3003/swagger
                        """
                    }
                )
            }
        }
    }
}
